### PR TITLE
Add babel on prepublish to allow UglifyJS to consume as node_module

### PR DESCRIPTION
**Pull request by kirbysayshi**
Hello there!

Feel free to ignore this (just close if you don't want to worry about this).

I'm using this module in an app that uses create-react-app (https://github.com/facebookincubator/create-react-app), which has an automatic UglifyJS build step. UglifyJS does not have ES2015 support, and create-react-app does not pass anything within `node_modules` through babel. Thus, the use of `let` in _this_ module causes an optimized build to fail because Uglify cannot parse the `let`. Bizarre, I know.

I'm guessing this isn't something you want to worry about, but it is something other people will run into if they use uglify on this package. So I figure a PR couldn't hurt; at the least, even if you don't use these changes maybe the commit saves a few searches for how to configure babel :D

I have the test still using the uncompiled version because I figured you didn't want a build step for test running.

Thank you for a useful package!

### CODE REVIEW

**Comment by dfcreative** [comment]
Just use 'browserify -g bubleify', why all the hassle?

**Comment by kirbysayshi** [comment]
The hassle is because a global transform is potentially slow, and because of this webpack and browserify don't compile within node_modules by default. Create-react-app does not provide a hook to modify the webpack config, meaning a user cannot add an exception for this individual package.

**Comment by dfcreative** [comment]
Sad to know, but seriously, that is a webpack infrastructural problem, not the `audio-buffer-utils`. I am facing that 4th time in my practice with webpack, browserify never had such issues afaik. Not sure how should we deal with that, are there best practices for that?
I would rather go for local `bubleify`/`es2020`/`etc` transform than introducing `dist` in repositorium. But still it does not feel right supporting old ES just because of infrastructural drawbacks. That way we never transit to ES6.

**Comment by kirbysayshi** [comment]
It's technically a problem that all packages face, but webpack has put the onus on the top-level to determine what a package needs, unlike browserify (which assumes all packages specify their transforms in package.json or publish es5 code).

An alternative to committing the `dist` folder is to .gitignore it. It will still be created and published during `npm publish`, but won't show up in the repo. It's a fairly common practice for authoring ES2015++ code but shipping ES5. I committed the `dist` folder in this PR because I needed it to exist from github without a publish step.

**Comment by dfcreative** [comment]
That looks like more maintaining efforts, more things to know (== to forget) and more things to possibly break in building process − that should not be like that, that should be very simple, that is not a huge package. Also babel[ify] is a heavy-weight tool and takes a while to install, at most I would opt for _bubleify_.
Honestly I am not ready for spending time on maintaining this building process (personally don't see value).
@jamen what do you think on that?

**Comment by jamen** [comment]
@kirbysayshi I agree with you on the uglify issue.  I've had that problem multiple times too, and I think a more modern minifier needs to be made eventually...  That can actually parse all valid JS code, instead of crashing.

I would lean towards no build system, though.  Personally I try to write all my packages as ES5-ish as I can, and then top it off the websites with something like [`es2020`](https://www.npmjs.com/package/es2020) or [`es2040`](https://www.npmjs.com/package/es2040).  I'm not sure if that works on dependencies like this though.

If we want audio.js to have just as good support on browser as it does Node, I think this is good discussion to have...  But I would personally just remove the ES6 pieces than put up a build system.

**Comment by connorhartley** [comment]
I agree with @jamen I don't think we necessarily need the ES6 pieces. I think that this is important to the value of making audiojs' modules isomorphic.

**Comment by kirbysayshi** [comment]
I suppose that was my original intent with this PR: to demonstrate that I had some problems consuming this package using relatively popular tools and their defaults. Making this package isomorphic seems like a great goal!

**Comment by dfcreative** [comment]
Alright, in @4.0.3 I've removed ES5 statements, uglify now does the thing.

**Comment by dfcreative** [comment]
@kirbysayshi please tell if that works for you

**Comment by kirbysayshi** [comment]
Looks good, thanks!

**Pull request closed without merging**
